export const DUMMY_POST = [
	{
		id: Date.now(),
		name: 'Иван',
		surname: 'Маловичко',
		city: 'Нижний Новгород',
		text: 'Quibusdam odio voluptatibus distinctio tempora, praesentium vero doloremque cum, deserunt repellendus esse voluptas minima. Adipisci doloremque doloribus quibusdam ut aspernatur repellat, dolor quam. Iure error repudiandae, dolore reiciendis nulla, corporis asperiores, voluptate quam quia aspernatur corrupti sit suscipit deserunt labore iusto voluptas!',
		createAppAt: '02.02.23',
	},
	{
		id: Date.now(),
		name: 'Аркадий',
		surname: 'Маловичко',
		city: 'Иркутск',
		text: 'asd asperiores, voluptate quam quia aspernatur corrupti sit suscipit deserunt labore iusto voluptas!',
		createAppAt: '01.02.19',
	},
	{
		id: Date.now(),
		name: 'Семён',
		surname: 'Маловичко',
		city: 'Якутск',
		text: 'nima. Adipisci doloremque doloribus quibusdam ut aspernatur repellat, dolor quam. Iure error repudiandae, dolore reiciendis nulla, corporis asperiores, voluptate quam quia aspernatur corrupti sit suscipit deserunt labore iusto voluptas!',
		createAppAt: '12.03.25',
	},
	{
		id: Date.now(),
		name: 'Алексей',
		surname: 'Маловичко',
		city: 'Усть-Лабинск',
		text: 'tur repellat, dolor quam. Iure error repudiandae, dolore reiciendis nulla, corporis asperiores, voluptate quam quia aspernatur corrupti sit suscipit deserunt labore iusto voluptas!',
		createAppAt: '31.12.21',
	},
	{
		id: Date.now(),
		name: 'Дмитрий',
		surname: 'Маловичко',
		city: 'Братск',
		text: 'Quiblat, dolor quam. Iure error repudiandae, dolore reiciendis nulla, corporis asperiores, voluptate quam quia aspernatur corrupti sit suscipit deserunt labore iusto voluptas!',
		createAppAt: '02.02.23',
	},
	{
		id: Date.now(),
		name: 'Сергей',
		surname: 'Маловичко',
		city: 'Иркутск',
		text: 'Qor repudiandae, dolore reiciendis nulla, corporis asperiores, voluptate quam quia aspernatur corrupti sit suscipit deserunt labore iusto voluptas!',
		createAppAt: '31.12.21',
	},
]
